Repository ECS-OH-Bot/OH-Bot, pull requests merged in 2020-10, with the labels that each got.

#48 Dq fix
  src/cogs/oh_queue.py
  src/cogs/tools.py
Labels: bug, enhancement

#52 Add clear queue variants
  configs/help_messages.yaml
  src/cogs/oh_queue.py
  src/cogs/tools.py
Labels: enhancement

#53 Coded a set of messages to be sent to the sender and to be logged in …
  src/cogs/oh_queue.py
Labels: invalid
